# Generated by Django 4.1.3 on 2022-11-30 15:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.subdivision', verbose_name='Подразделение'),
        ),
    ]
